#!/usr/bin/env ruby
require_relative 'lib/ruby_nos_client/cli'

require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

RubyNosClient::Cli.start
